site_name: Tinder Engineering Docs
repo_name: "TinderBackend/docs.engineering"
repo_url: "https://github.com/TinderBackend/docs.engineering"
site_url: "http://eng.tinderdocs.net"

theme:
  name: material
  custom_dir: docs/overrides
  favicon: favicon.png
  palette:
    primary: blue grey
    accent: cyan
  features:
    - tabs
    - instant

plugins:
  - awesome-pages
  - git-authors
  - git-revision-date-localized
  - search
  - tags:
      tags_file: tags.md

markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - tables
  - pymdownx.tasklist:
      clickable_checkbox: true
  - pymdownx.details
#  - pymdownx.highlight:
#      anchor_linenums: true
#  - pymdownx.inlinehilite
#  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
     permalink: true
nav:
  - Home: README.md
  - Tags: tags.md
  - FAQ: faq.md
  - How To Contribute: how-to-contribute.md
  - Architecture Definitions:
      - Backend:
          - Backend Infra:
              - Event Bus: architecture-definitions/backend/eventbus/eventbus.md
              - Dynamo Stream Workers: architecture-definitions/backend/eventbus/dynamo_stream_workers.md
              - Hydrated User Events Flink Job: architecture-definitions/backend/eventbus/hydrated_user_events_flink_job.md
              - User Field Filter Worker: architecture-definitions/backend/eventbus/user_field_filter_worker.md
              - Maxmind API Gateway Filter: architecture-definitions/backend/maxmind/maxmind_filter.md
          - Region Service:
              - Regions Redesign: architecture-definitions/backend/regionservice/regions_redesign.md
          - Trust:
              - Device Check: architecture-definitions/backend/trust/devicecheck.md
              - RADAR: architecture-definitions/backend/trust/radar.md
          - TSP:
              - SMS Config Service: architecture-definitions/backend/tsp/smsconfig.md
              - SMS OTP Redesign: architecture-definitions/backend/sms/sms_otp_redesign.md
      - Clients:
          - iOS:
              - Placeholder: architecture-definitions/clients/android/overview.md
          - Android:
              - Placeholder: architecture-definitions/clients/android/overview.md
  - Best Practices & Guidelines:
      - Development Process (The Process): best-practices/the-process.md
      - Reviewing Pull Requests: best-practices/pull-request-review.md
      - Code Readability & Maintainability:
          - General Guidelines: best-practices/readability-and-maintainability/general-guidelines.md
          - Pull Request Considerations for Repos: best-practices/readability-and-maintainability/pr-considerations-for-repos.md
          - Runtime & Dependency Management: best-practices/readability-and-maintainability/runtime-dependency-management.md
          - Testing: best-practices/readability-and-maintainability/testing-best-practices.md
      - Continuous Integration & Delivery (CI/CD):
          - Continuous Integration:
              - CI Process: best-practices/cicd/continuous-integration.md
          - Continuous Delivery:
              - CD Process: best-practices/cicd/continuous-delivery.md
              - Regression Testing: best-practices/cicd/cd-regression-testing.md
          - Continuous Deployment: best-practices/cicd/continuous-deployment.md
      - Backend:
          - Gradle:
              - Gradle Home: best-practices/backend/gradle/gradle.md
              - Revive Artifact Development: best-practices/backend/gradle/artifact_development.md
              - Gradle Build File (build.gradle) Basics: best-practices/backend/gradle/build_file_basics.md
              - Gradle Tasks: best-practices/backend/gradle/gradle_tasks.md
              - Gradle Project Structure: best-practices/backend/gradle/gradle_project_structure.md
              - Gradle Dependency Management: best-practices/backend/gradle/gradle_dependency_management.md
          - Pod Resources: best-practices/backend/pod_resources.md
          - Flink: best-practices/backend/flink.md
  - How-to Guides:
      - Backend:
          - Apple Silicon (M1/ARM64) Laptup Setup Guide: how-to-guides/backend/arm_64_laptop_setup.md
          - How to Write a gRPC Service: how-to-guides/backend/grpc.md
  - Module Overviews & Documents:
      - Backend:
          - apigateway: module-docs/backend/services/apigateway.md
  - Runbooks:
      - Backend:
          - Growth:
              - Rewarded Video Ads: runbooks/backend/growth/rewardedvideo-runbook.md
              - Dynamic Ads Cadence: runbooks/backend/growth/dynamicadscadence-runbook.md
          - Trust:
              - Device Check Runbook: runbooks/backend/trust/devicecheck-runbook.md
              - Flink Runbook: runbooks/backend/trust/flink-runbook.md
          - TSP:
              - TSP SMS Runbook: runbooks/backend/tsp/tsp_sms.md
  - Templates:
      - Runbook: doc-templates/backend_runbook.md
  - Tools:
      - App Dynamics: tools/appdynamics.md
      - AWS CloudWatch: tools/cloudwatch.md
      - Duraflame Logger: tools/duraflame.md
      - Ignis: tools/ignis.md
      - Jaeger Tracing: tools/jaeger.md
      - jFrog Artifactory: tools/jfrog.md
      - Kibana (ELK): tools/kibana.md
      - Prometheus Metrics: tools/prometheus.md
      - Sourcegraph Code Search: tools/sourcegraph.md
  - Presentations:
      - Backend Talks: presentations/backend-talks.md
  - Technical Docs Around Tinder: other-docs.md
  - Imported Knowledge Bases:
      - ... | instrumentation/**
